networks:
  backend:
    internal: true
  cloudflare: null
  dozzle: null
  frontend:
    internal: true

services:
  cloudflared:
    command: tunnel --no-autoupdate --config=/cloudflared-config.yml run
    container_name: cloudflared
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    image: cloudflare/cloudflared@sha256:9b49eed8f62806d5d45ddf59ecefb5710429598ea6d3fcccd2af938f621b2b07
    networks:
      - cloudflare
      - frontend
    restart: ${RESTART:-unless-stopped}
    volumes:
      - ./cloudflared/config.yml:/cloudflared-config.yml
  dozzle:
    container_name: dozzle
    image: amir20/dozzle@sha256:a7d69d20891d3dcc82636e24afa4c1c162b41d0673ef798b14f09e6b69accc5a
    networks:
      - dozzle
    ports:
      - 8080:8080
    restart: ${RESTART:-unless-stopped}
    user: "0"
    volumes:
      - ./data/dozzle:/data
      - /var/run/docker.sock:/var/run/docker.sock
  instaprint_backend:
    container_name: instaprint_backend
    environment:
      - DUMMY_PRINTER=${DUMMY_PRINTER:-False}
      - ENVIRONMENT=${ENVIRONMENT:-DEV}
      - JOB_TIME_BUFFER=${JOB_TIME_BUFFER}
      - LOG_LEVEL_BLEAK=${LOG_LEVEL_BLEAK:-ERROR}
      - LOG_LEVEL_PYINSTAXBLE=${LOG_LEVEL_PYINSTAXBLE:-ERROR}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MONITOR_INFO_DELAY=${MONITOR_INFO_DELAY}
      - PRINT_TIME_BUFFER=${PRINT_TIME_BUFFER}
      - PRINTER_ADDRESS=${PRINTER_ADDRESS}
      - PRINTER_NAME=${PRINTER_NAME}
      - PRINTING_ENABLED=${PRINTING_ENABLED}
      - PRINTING_TIMEOUT=${PRINTING_TIMEOUT}
    image: instaprint_backend:latest
    networks:
      - backend
    restart: ${RESTART:-unless-stopped}
    security_opt:
      - apparmor=docker-allow-dbus
    volumes:
      - ./data/print_server:/data
      - /var/run/dbus/:/run/dbus/
  instaprint_frontend:
    container_name: instaprint_frontend
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-DEV}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    image: instaprint_frontend:latest
    networks:
      - backend
      - frontend
    restart: ${RESTART:-unless-stopped}
    volumes:
      - ./frontend_server/plugins:/plugins
      - ./frontend_server/resources:/resources
      - ./frontend_server/static:/static