networks:
  default:
  internal:
    internal: true
  dozzle:

services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:2026.8.3
    restart: ${RESTART:-unless-stopped}
    networks:
      - default
      - internal
    volumes:
      - ./cloudflared/config.yml:/cloudflared-config.yml
      #- ./cloudflared/credentials.json:/cloudflared-credentials.json
      #- ./cloudflared/cert.pem:/etc/cloudflared/cert.pem
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate --config=/cloudflared-config.yml run

  print_server:
    container_name: print_server
    image: instaprint:latest
    restart: ${RESTART:-unless-stopped}
    # networks:
    #   - internal
    ports:
      - 8000:80
    environment:
      - DUMMY_PRINTER=${DUMMY_PRINTER:-False}
      - ENVIRONMENT=${ENVIRONMENT}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_LEVEL_BLEAK=${LOG_LEVEL_BLEAK}
      - LOG_LEVEL_PYINSTAXBLE=${LOG_LEVEL_PYINSTAXBLE}
      - PRINTER_ADDRESS=${PRINTER_ADDRESS}
      - PRINTER_NAME=${PRINTER_NAME}
      - PRINTING_ENABLED=${PRINTING_ENABLED}
    volumes:
      - ./data/print_server:/data
      - /var/run/dbus/:/run/dbus/
      - ./print_server/static:/static
      - ./print_server/resources:/resources
      - ./print_server/plugins:/plugins
    security_opt:
      - apparmor=docker-allow-dbus
  dozzle:
    container_name: dozzle
    image: amir20/dozzle@sha256:14715831551df5ae6a9bc495db42bb8168fcedf0680d9f05f142f6b999e410aa
    user: "0" # requires root user for reading docker socket
    networks:
      - dozzle
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/dozzle:/data
