

services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:2025.2.0
    restart: unless-stopped

    volumes:
      - ./cloudflared/config.yml:/cloudflared-config.yml
      - ./cloudflared/credentials.json:/cloudflared-credentials.json
      - ./cloudflared/cert.pem:/etc/cloudflared/cert.pem

    command: tunnel --no-autoupdate --config=/cloudflared-config.yml run

  print_server:
    container_name: print_server
    image: instaprint:latest
    restart: unless-stopped
    volumes:
      - ./data/print_server:/data
    ports:
      - 8000:80