# [build-system]
# requires = ["hatchling==1.29.0"]
# build-backend = "hatchling.build"

[project]
name = "instalink-server"
version = "0.0.1"
requires-python = ">=3.11.0"
dependencies = [
    "fastapi[standard]==0.136.3",
    "anyio>=4.13",
    "requests>=2.34.2",
    "httpx>=0.28.1",
]

[project.optional-dependencies]

[dependency-groups]
backend = [
    "pyinstaxble",
    "pytz>=2026.3.post1",
]
lint = [
    "ruff>=0.16.0",
]

[tool.uv.sources]
pyinstaxble = [
    { git = "ssh://git@github.com/JoRobs/pyinstaxble.git", tag = "v0.3.2" }
]


# [tool.hatch.build.targets.wheel]
# packages = ["instalink_server"]

[tool.ruff]
# Set the maximum line length to 79.
line-length = 79

[tool.ruff.lint]
ignore = [
  "BLE001",
  "TRY002", # Create your own exception
  "E722", # Do not use bare `except`
]
