# [build-system]
# requires = ["hatchling==1.29.0"]
# build-backend = "hatchling.build"

[project]
name = "instalink-server"
version = "0.0.1"
requires-python = "~=3.11.0"
dependencies = [
    "fastapi[standard]==0.136.3",
    "anyio==4.13",
    "pyinstaxble",
]

[project.optional-dependencies]
lint = [
    "ruff>=0.16.0",
]

[tool.uv.sources]
pyinstaxble = { git = "ssh://git@github.com/JoRobs/pyinstaxble.git", tag = "v0.1.2dev" }

# [tool.hatch.build.targets.wheel]
# packages = ["instalink_server"]

[tool.ruff]
# Set the maximum line length to 79.
line-length = 79

[tool.ruff.lint]
ignore = [
  "BLE001",
]